VALID_USERNAME = "JackABC"
VALID_PASSWORD = "AbCdEr55"

INVALID_USERNAME = "abc"
INVALID_PASSWORD = "AbCd555"

NEW_USER = "James"
NEW_PASSWORD = "Sm22241@"
EMAIL = "ab@hotmail.com"

EDIT_USER = "abcd"
EDIT_EMAIL = "xxx"

